### ISSUE TITLE
Arm support in oneDNN

### ISSUE THREAD

**Issue by vpirogov** [fujitsu/dnnl_aarch64#10]
Just wanted to let you know that initial support for Arm 64-bit Architecture (AArch64) landed in oneDNN master along with the changes that will enable to easier maintain optimizations for non-x86 architectures. See details [here](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/README.md).

**Comment by kawakami-k** [comment]
Thank you, vpirogov-san. That's very good news for us.  We will prepare to upstream our source code.

**Comment by vpirogov** [comment]
@kawakami-k&dash;san,
 
I'm glad this is useful. As a starting point I would suggest publishing an RFC that describes the proposed changes and new dependencies introduced. This will help collect input from broader oneDNN community interested in AArch64 optimizations.

**Comment by vpirogov** [comment]
+@nSircombe

**Comment by Danliran** [comment]
oneDNN support aarch64, but JIT assembler 'aarch64_Xbayk' isn`t integrated into oneDNN, the performance is not good on aarch64 platform.

**Comment by vpirogov** [comment]
Closing this item as thanks to Fujitsu and Arm developers [oneDNN v3.0](https://github.com/oneapi-src/oneDNN/releases/tag/v3.0) has production quality support for AArch64.
